# Generated by Django 4.2.30 on 2026-10-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interval_days', models.PositiveIntegerField(default=30)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('state', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace Period'), ('triggered', 'Triggered'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('last_checkin', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_deadline', models.DateTimeField()),
                ('grace_deadline', models.DateTimeField(blank=True, null=True)),
                ('total_checkins', models.PositiveIntegerField(default=0)),
                ('missed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_heartbeat_config',
            },
        ),
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('checkin', 'Check-in'), ('missed', 'Missed'), ('grace_started', 'Grace Period Started'), ('grace_expired', 'Grace Period Expired'), ('triggered', 'Release Triggered'), ('config_changed', 'Configuration Changed')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='heartbeat.heartbeatconfig')),
            ],
            options={
                'db_table': 'aegis_heartbeat_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
