# Generated by Django 4.2.30 on 2026-10-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('invitation_alerts', models.BooleanField(default=True)),
                ('trustee_alerts', models.BooleanField(default=True)),
                ('heartbeat_alerts', models.BooleanField(default=True)),
                ('release_alerts', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('invitation', 'Invitation'), ('trustee', 'Trustee'), ('heartbeat', 'Heartbeat'), ('release', 'Release'), ('security', 'Security'), ('system', 'System'), ('share', 'Share')], default='system', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('vault_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='aegis_notif_user_id_4e7960_idx'), models.Index(fields=['notification_type'], name='aegis_notif_notific_a92102_idx'), models.Index(fields=['created_at'], name='aegis_notif_created_07c89d_idx')],
            },
        ),
    ]
