/**
 * AegisVault — Vault Management Module: Mock Data
 * Realistic demo datasets matching the Admin Vault Management screenshots:
 * - 4 Summary KPI metrics
 * - 30+ realistic vault records across multiple pages and categories
 * - Vault type breakdown for the interactive SVG donut chart
 * - Trustee metadata and zero-knowledge safe details
 */

const AegisVaultMockData = {
    overview: {
        totalVaults: 892,
        totalVaultsTrend: "+15%",
        totalVaultsSubtext: "+116 this month",
        activeVaults: 624,
        activeVaultsTrend: "+10%",
        activeVaultsSubtext: "70.0% of total",
        archivedVaults: 268,
        archivedVaultsTrend: "+8%",
        archivedVaultsSubtext: "30.0% of total",
        pendingAccess: 12,
        pendingAccessTrend: "-25%",
        pendingAccessSubtext: "Requires review"
    },

    vaultTypesDistribution: [
        { label: "Personal", percentage: 43.6, count: 389, color: "#2563EB", darkColor: "#3B82F6" },
        { label: "Financial", percentage: 21.9, count: 195, color: "#0D9488", darkColor: "#14B8A6" },
        { label: "Business", percentage: 18.2, count: 162, color: "#F59E0B", darkColor: "#FBBF24" },
        { label: "Legal", percentage: 10.1, count: 90, color: "#8B5CF6", darkColor: "#A78BFA" },
        { label: "Others", percentage: 6.2, count: 56, color: "#EF4444", darkColor: "#F87171" }
    ],

    // The primary list of vaults - first 10 strictly match the screenshot!
    vaults: [
        {
            id: "VLT-2025-001",
            index: 1,
            name: "Personal Documents",
            owner: "Rahul Mehta",
            ownerEmail: "rahul.mehta@aegisvault.io",
            type: "Personal",
            status: "Active",
            createdOn: "12 Sep 2025",
            lastAccessed: "12 Sep 2025",
            trusteesCount: 3,
            verifiedTrustees: 3,
            threshold: "2 of 3",
            heartbeatInterval: "30 Days",
            lastHeartbeat: "4 hours ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Shamir Threshold Verification (2-of-3)",
            itemCount: 24,
            storageSize: "48.2 MB"
        },
        {
            id: "VLT-2025-002",
            index: 2,
            name: "Financial Records",
            owner: "Sneha Patel",
            ownerEmail: "sneha.patel@horizon.tech",
            type: "Financial",
            status: "Active",
            createdOn: "10 Sep 2025",
            lastAccessed: "11 Sep 2025",
            trusteesCount: 5,
            verifiedTrustees: 4,
            threshold: "3 of 5",
            heartbeatInterval: "14 Days",
            lastHeartbeat: "1 day ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Shamir Threshold Verification (3-of-5)",
            itemCount: 42,
            storageSize: "112.8 MB"
        },
        {
            id: "VLT-2025-003",
            index: 3,
            name: "Business Assets",
            owner: "Arjun Shah",
            ownerEmail: "arjun.shah@vortexcapital.in",
            type: "Business",
            status: "Active",
            createdOn: "08 Sep 2025",
            lastAccessed: "10 Sep 2025",
            trusteesCount: 4,
            verifiedTrustees: 4,
            threshold: "3 of 4",
            heartbeatInterval: "60 Days",
            lastHeartbeat: "2 days ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Multi-Signature Corporate Key (3-of-4)",
            itemCount: 68,
            storageSize: "284.5 MB"
        },
        {
            id: "VLT-2025-004",
            index: 4,
            name: "Legal Documents",
            owner: "Priya Desai",
            ownerEmail: "priya.desai@juriscorp.org",
            type: "Legal",
            status: "Archived",
            createdOn: "05 Sep 2025",
            lastAccessed: "28 Aug 2025",
            trusteesCount: 2,
            verifiedTrustees: 2,
            threshold: "2 of 2",
            heartbeatInterval: "90 Days",
            lastHeartbeat: "24 days ago",
            heartbeatStatus: "Archived",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Executor Attestation & Threshold",
            itemCount: 15,
            storageSize: "32.1 MB"
        },
        {
            id: "VLT-2025-005",
            index: 5,
            name: "Health Records",
            owner: "Karan Joshi",
            ownerEmail: "karan.joshi@medsafe.org",
            type: "Personal",
            status: "Active",
            createdOn: "04 Sep 2025",
            lastAccessed: "12 Sep 2025",
            trusteesCount: 3,
            verifiedTrustees: 2,
            threshold: "2 of 3",
            heartbeatInterval: "30 Days",
            lastHeartbeat: "6 hours ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Emergency Medical Proxy Attestation",
            itemCount: 19,
            storageSize: "95.4 MB"
        },
        {
            id: "VLT-2025-006",
            index: 6,
            name: "Crypto Wallet",
            owner: "Rohit Verma",
            ownerEmail: "rohit.verma@cryptonodes.io",
            type: "Financial",
            status: "Pending",
            createdOn: "02 Sep 2025",
            lastAccessed: "09 Sep 2025",
            trusteesCount: 4,
            verifiedTrustees: 2,
            threshold: "3 of 4",
            heartbeatInterval: "7 Days",
            lastHeartbeat: "3 days ago (Grace Period)",
            heartbeatStatus: "Due Soon",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Threshold Key Sharding (3-of-4)",
            itemCount: 8,
            storageSize: "4.2 MB"
        },
        {
            id: "VLT-2025-007",
            index: 7,
            name: "Family Vault",
            owner: "Ananya Iyer",
            ownerEmail: "ananya.iyer@heritagecustody.in",
            type: "Personal",
            status: "Active",
            createdOn: "01 Sep 2025",
            lastAccessed: "11 Sep 2025",
            trusteesCount: 4,
            verifiedTrustees: 4,
            threshold: "2 of 4",
            heartbeatInterval: "30 Days",
            lastHeartbeat: "1 day ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Family Trustee Majority (2-of-4)",
            itemCount: 53,
            storageSize: "340.0 MB"
        },
        {
            id: "VLT-2025-008",
            index: 8,
            name: "Startup IP",
            owner: "Vikram Nair",
            ownerEmail: "vikram.nair@quantumltd.tech",
            type: "Business",
            status: "Archived",
            createdOn: "28 Aug 2025",
            lastAccessed: "01 Sep 2025",
            trusteesCount: 3,
            verifiedTrustees: 3,
            threshold: "2 of 3",
            heartbeatInterval: "90 Days",
            lastHeartbeat: "21 days ago",
            heartbeatStatus: "Archived",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Board Trustee Consensus",
            itemCount: 31,
            storageSize: "512.6 MB"
        },
        {
            id: "VLT-2025-009",
            index: 9,
            name: "Education Certificates",
            owner: "Neha Sharma",
            ownerEmail: "neha.sharma@academiashare.edu",
            type: "Personal",
            status: "Active",
            createdOn: "25 Aug 2025",
            lastAccessed: "10 Sep 2025",
            trusteesCount: 2,
            verifiedTrustees: 2,
            threshold: "1 of 2",
            heartbeatInterval: "60 Days",
            lastHeartbeat: "5 days ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Designated Successor Confirmation",
            itemCount: 12,
            storageSize: "18.9 MB"
        },
        {
            id: "VLT-2025-010",
            index: 10,
            name: "Emergency Access",
            owner: "Aditya Rao",
            ownerEmail: "aditya.rao@safeguard.io",
            type: "Legal",
            status: "Pending",
            createdOn: "20 Aug 2025",
            lastAccessed: "08 Sep 2025",
            trusteesCount: 3,
            verifiedTrustees: 1,
            threshold: "2 of 3",
            heartbeatInterval: "14 Days",
            lastHeartbeat: "Due Today",
            heartbeatStatus: "Requires Review",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Legal Guardian Attestation",
            itemCount: 6,
            storageSize: "8.5 MB"
        },
        // Additional realistic records for pagination and multi-filtering:
        {
            id: "VLT-2025-011",
            index: 11,
            name: "Real Estate Titles",
            owner: "Meera Sen",
            ownerEmail: "meera.sen@propvault.in",
            type: "Legal",
            status: "Active",
            createdOn: "18 Aug 2025",
            lastAccessed: "07 Sep 2025",
            trusteesCount: 3,
            verifiedTrustees: 3,
            threshold: "2 of 3",
            heartbeatInterval: "45 Days",
            lastHeartbeat: "3 days ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Title Transfer Protocol (2-of-3)",
            itemCount: 22,
            storageSize: "74.1 MB"
        },
        {
            id: "VLT-2025-012",
            index: 12,
            name: "Offshore Holdings",
            owner: "Kabir Malhotra",
            ownerEmail: "kabir.m@apexoffshore.com",
            type: "Financial",
            status: "Active",
            createdOn: "15 Aug 2025",
            lastAccessed: "06 Sep 2025",
            trusteesCount: 5,
            verifiedTrustees: 5,
            threshold: "4 of 5",
            heartbeatInterval: "30 Days",
            lastHeartbeat: "1 day ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Consensus Trustee Release (4-of-5)",
            itemCount: 58,
            storageSize: "145.2 MB"
        },
        {
            id: "VLT-2025-013",
            index: 13,
            name: "Patent Portfolio",
            owner: "Dr. Sunita Reddy",
            ownerEmail: "sunita.reddy@biozen.res.in",
            type: "Business",
            status: "Active",
            createdOn: "12 Aug 2025",
            lastAccessed: "05 Sep 2025",
            trusteesCount: 4,
            verifiedTrustees: 4,
            threshold: "3 of 4",
            heartbeatInterval: "90 Days",
            lastHeartbeat: "4 days ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Institutional Custody Shards (3-of-4)",
            itemCount: 45,
            storageSize: "620.0 MB"
        },
        {
            id: "VLT-2025-014",
            index: 14,
            name: "Personal Memoirs",
            owner: "Devendra Kulkarni",
            ownerEmail: "dev.kulkarni@storysafe.in",
            type: "Personal",
            status: "Archived",
            createdOn: "08 Aug 2025",
            lastAccessed: "15 Aug 2025",
            trusteesCount: 2,
            verifiedTrustees: 2,
            threshold: "1 of 2",
            heartbeatInterval: "180 Days",
            lastHeartbeat: "35 days ago",
            heartbeatStatus: "Archived",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Time-Locked Memorial Release",
            itemCount: 88,
            storageSize: "1.2 GB"
        },
        {
            id: "VLT-2025-015",
            index: 15,
            name: "Private Keys Backup",
            owner: "Sameer Saxena",
            ownerEmail: "sameer.saxena@zeroledger.org",
            type: "Financial",
            status: "Pending",
            createdOn: "04 Aug 2025",
            lastAccessed: "02 Sep 2025",
            trusteesCount: 3,
            verifiedTrustees: 1,
            threshold: "2 of 3",
            heartbeatInterval: "7 Days",
            lastHeartbeat: "Missed Check-In (Grace)",
            heartbeatStatus: "Requires Review",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Emergency Shard Verification (2-of-3)",
            itemCount: 5,
            storageSize: "1.8 MB"
        },
        {
            id: "VLT-2025-016",
            index: 16,
            name: "Boardroom Resolutions",
            owner: "Ritu Singhania",
            ownerEmail: "ritu.singhania@corpzen.in",
            type: "Business",
            status: "Active",
            createdOn: "01 Aug 2025",
            lastAccessed: "01 Sep 2025",
            trusteesCount: 5,
            verifiedTrustees: 4,
            threshold: "3 of 5",
            heartbeatInterval: "60 Days",
            lastHeartbeat: "8 days ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Corporate Dual-Key Quorum (3-of-5)",
            itemCount: 39,
            storageSize: "88.7 MB"
        },
        {
            id: "VLT-2025-017",
            index: 17,
            name: "Art & Collectibles Certs",
            owner: "Nikhil Verma",
            ownerEmail: "nikhil.verma@artvault.co",
            type: "Personal",
            status: "Active",
            createdOn: "28 Jul 2025",
            lastAccessed: "29 Aug 2025",
            trusteesCount: 3,
            verifiedTrustees: 3,
            threshold: "2 of 3",
            heartbeatInterval: "30 Days",
            lastHeartbeat: "10 days ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Curator Attestation & Proof",
            itemCount: 17,
            storageSize: "142.3 MB"
        },
        {
            id: "VLT-2025-018",
            index: 18,
            name: "Tax Compliance Archive",
            owner: "Pooja Hegde",
            ownerEmail: "pooja.hegde@auditpartners.in",
            type: "Financial",
            status: "Archived",
            createdOn: "22 Jul 2025",
            lastAccessed: "10 Aug 2025",
            trusteesCount: 2,
            verifiedTrustees: 2,
            threshold: "2 of 2",
            heartbeatInterval: "365 Days",
            lastHeartbeat: "42 days ago",
            heartbeatStatus: "Archived",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Annual Fiscal Disclosure Trigger",
            itemCount: 46,
            storageSize: "98.1 MB"
        },
        {
            id: "VLT-2025-019",
            index: 19,
            name: "Trust Deed & Codicil",
            owner: "Manish Chawla",
            ownerEmail: "manish.chawla@estatechambers.com",
            type: "Legal",
            status: "Active",
            createdOn: "19 Jul 2025",
            lastAccessed: "25 Aug 2025",
            trusteesCount: 4,
            verifiedTrustees: 4,
            threshold: "3 of 4",
            heartbeatInterval: "90 Days",
            lastHeartbeat: "12 days ago",
            heartbeatStatus: "Healthy",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Notarial Certification Required",
            itemCount: 28,
            storageSize: "64.0 MB"
        },
        {
            id: "VLT-2025-020",
            index: 20,
            name: "Cloud Infra Root Credentials",
            owner: "Tushar Goswami",
            ownerEmail: "tushar.g@cloudinfra.net",
            type: "Business",
            status: "Pending",
            createdOn: "15 Jul 2025",
            lastAccessed: "22 Aug 2025",
            trusteesCount: 4,
            verifiedTrustees: 2,
            threshold: "3 of 4",
            heartbeatInterval: "14 Days",
            lastHeartbeat: "Grace Period (Day 3)",
            heartbeatStatus: "Requires Review",
            encryption: "AES-256-GCM (Client-Side)",
            releaseCondition: "Disaster Recovery Quorum (3-of-4)",
            itemCount: 11,
            storageSize: "3.4 MB"
        }
    ],

    // Safe Trustee List for Demo
    trusteesDirectory: [
        { name: "Dr. Alok Verma", email: "alok.verma@aiims.edu", role: "Primary Custodian", status: "Verified" },
        { name: "Suman Nair", email: "suman.nair@lawchambers.in", role: "Legal Attestor", status: "Verified" },
        { name: "Kavita Rao", email: "kavita.rao@finsec.org", role: "Financial Executor", status: "Pending" },
        { name: "Rohan Bansal", email: "rohan.bansal@techtrust.io", role: "Technical Trustee", status: "Verified" }
    ],

    // Template Options for Quick Actions
    templates: [
        { title: "Standard Estate Vault", type: "Personal", trustees: "3 Trustees (2-of-3)", desc: "Pre-configured for family legacy, identity records, and essential documents." },
        { title: "Corporate Succession Vault", type: "Business", trustees: "5 Trustees (3-of-5)", desc: "Designed for corporate shareholding, server access, and board resolution escrow." },
        { title: "Cryptographic Asset Vault", type: "Financial", trustees: "4 Trustees (3-of-4)", desc: "Optimized for hardware wallet seeds, multi-sig shards, and 2FA recovery." }
    ]
};

// Export to global scope
if (typeof window !== 'undefined') {
    window.AegisVaultMockData = AegisVaultMockData;
}
