# Generated by Django 4.2.30 on 2026-10-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('vault_type', models.CharField(choices=[('Personal', 'Personal'), ('Family', 'Family'), ('Business', 'Business'), ('Legacy', 'Legacy'), ('Health', 'Health')], default='Personal', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Locked', 'Locked'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('release_condition', models.TextField(blank=True, default='')),
                ('inactivity_days', models.PositiveIntegerField(default=60)),
                ('required_shares', models.PositiveIntegerField(default=1)),
                ('total_shares', models.PositiveIntegerField(default=1)),
                ('storage_used_bytes', models.BigIntegerField(default=0)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_vaults',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('document', 'Document'), ('credential', 'Credential'), ('financial', 'Financial'), ('personal', 'Personal'), ('recovery', 'Recovery'), ('custom', 'Custom')], default='document', max_length=20)),
                ('encrypted_data', models.TextField()),
                ('encryption_iv', models.CharField(blank=True, default='', max_length=64)),
                ('encryption_tag', models.CharField(blank=True, default='', max_length=64)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vaults.vault')),
            ],
            options={
                'db_table': 'aegis_vault_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('View Only', 'View Only'), ('View & Download', 'View & Download'), ('Full Access', 'Full Access')], default='View Only', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trustee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='vaults.vault')),
            ],
            options={
                'db_table': 'aegis_vault_shares',
                'ordering': ['-created_at'],
                'unique_together': {('vault', 'trustee')},
            },
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['owner', 'status'], name='aegis_vault_owner_i_806fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['vault_type'], name='aegis_vault_vault_t_de45cd_idx'),
        ),
    ]
