# Generated by Django 4.2.30 on 2026-10-08 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vaults.models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('document', 'Document'), ('credential', 'Credential'), ('financial', 'Financial'), ('personal', 'Personal'), ('recovery', 'Recovery'), ('custom', 'Custom')], default='document', max_length=20)),
                ('sensitivity', models.CharField(choices=[('Normal', 'Normal'), ('Sensitive', 'Sensitive'), ('Highly Sensitive', 'Highly Sensitive'), ('Critical', 'Critical')], default='Normal', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('encrypted_data', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to=vaults.models.vault_asset_path)),
                ('encryption_iv', models.CharField(blank=True, default='', max_length=64)),
                ('encryption_tag', models.CharField(blank=True, default='', max_length=64)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aegis_vault_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vault',
            name='priority',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='vault',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vault',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=10737418240),
        ),
        migrations.AddField(
            model_name='vault',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='VaultItem',
        ),
        migrations.AddField(
            model_name='vaultasset',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='vaults.vault'),
        ),
    ]
