# Generated by Django 4.2.30 on 2026-10-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaults', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrusteeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('relationship', models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Colleague', 'Colleague'), ('Cousin', 'Cousin'), ('Legal Advisor', 'Legal Advisor'), ('Other', 'Other')], default='Other', max_length=30)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Not Started', 'Not Started'), ('Revoked', 'Revoked')], default='Not Started', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Invited', 'Invited'), ('Removed', 'Removed'), ('Suspended', 'Suspended')], default='Invited', max_length=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designated_trustees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trustee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_trustee_profiles',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_name', models.CharField(max_length=255)),
                ('invitee_email', models.EmailField(max_length=255)),
                ('relationship', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('token', models.CharField(default='', max_length=128, unique=True)),
                ('token_used', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('trustee_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='trustees.trusteeprofile')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='vaults.vault')),
            ],
            options={
                'db_table': 'aegis_invitations',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trusteeprofile',
            index=models.Index(fields=['owner', 'status'], name='aegis_trust_owner_i_b55c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteeprofile',
            index=models.Index(fields=['verification_status'], name='aegis_trust_verific_920022_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteeprofile',
            index=models.Index(fields=['email'], name='aegis_trust_email_303576_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trusteeprofile',
            unique_together={('owner', 'email')},
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['owner', 'status'], name='aegis_invit_owner_i_b79c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invitee_email'], name='aegis_invit_invitee_097cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='aegis_invit_token_1ad33d_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='aegis_invit_expires_1ff877_idx'),
        ),
    ]
