# Generated by Django 4.2.30 on 2026-10-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('brute_force', 'Brute Force Attempt'), ('unauthorized_access', 'Unauthorized Access'), ('suspicious_activity', 'Suspicious Activity'), ('config_change', 'Configuration Change'), ('data_export', 'Data Export'), ('rate_limit', 'Rate Limit Exceeded')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resource', models.CharField(blank=True, default='', max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_security_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'severity'], name='aegis_secur_event_t_ea4686_idx'), models.Index(fields=['is_resolved'], name='aegis_secur_is_reso_02c202_idx'), models.Index(fields=['timestamp'], name='aegis_secur_timesta_f609ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_key', models.CharField(max_length=50)),
                ('action_title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('vault', 'Vault'), ('trustee', 'Trustee'), ('share', 'Share'), ('release', 'Release'), ('heartbeat', 'Heartbeat'), ('security', 'Security'), ('admin', 'Admin'), ('profile', 'Profile'), ('system', 'System')], default='system', max_length=15)),
                ('vault_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning'), ('info', 'Info')], default='success', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('previous_hash', models.CharField(blank=True, default='', max_length=128)),
                ('entry_hash', models.CharField(blank=True, default='', max_length=128)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'category'], name='aegis_audit_user_id_1600c0_idx'), models.Index(fields=['action_key'], name='aegis_audit_action__bcd2dc_idx'), models.Index(fields=['timestamp'], name='aegis_audit_timesta_6b31b7_idx'), models.Index(fields=['category', 'status'], name='aegis_audit_categor_44f9af_idx')],
            },
        ),
    ]
