# Generated by Django 4.2.30 on 2026-10-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaults', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('Upon Inactivity', 'Upon Inactivity'), ('Manual Trigger', 'Manual Trigger'), ('Scheduled Date', 'Scheduled Date'), ('Death Certificate', 'Death Certificate'), ('Trustee Consensus', 'Trustee Consensus')], default='Upon Inactivity', max_length=30)),
                ('trigger_detail', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('authorized', 'Authorized'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('scheduled', 'Scheduled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('required_shares', models.PositiveIntegerField(default=1)),
                ('total_shares', models.PositiveIntegerField(default=1)),
                ('collected_shares', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_requests', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='vaults.vault')),
            ],
            options={
                'db_table': 'aegis_release_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='releases.releaserequest')),
                ('trustee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aegis_release_participants',
            },
        ),
        migrations.CreateModel(
            name='SecretShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_shard', models.TextField()),
                ('shard_index', models.PositiveIntegerField()),
                ('shard_metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trustee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_shares', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_shares', to='vaults.vault')),
            ],
            options={
                'db_table': 'aegis_secret_shares',
                'ordering': ['shard_index'],
                'unique_together': {('vault', 'trustee')},
            },
        ),
        migrations.AddIndex(
            model_name='releaserequest',
            index=models.Index(fields=['owner', 'status'], name='aegis_relea_owner_i_db57ea_idx'),
        ),
        migrations.AddIndex(
            model_name='releaserequest',
            index=models.Index(fields=['vault', 'status'], name='aegis_relea_vault_i_11979f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='releaseparticipant',
            unique_together={('release', 'trustee')},
        ),
    ]
